### PR TITLE
Basic python3 compatibility

### PR DESCRIPTION
**Pull request by homebysix**
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.

More adjustments may need to be made manually later, but this should catch the low-hanging fruit right now.

### CODE REVIEW

**Comment by homebysix** [comment]
Hi @apettinen - Just checking in to see whether you're comfortable merging this in, or have any questions?

Some additional processor changes will be needed for the upcoming version 2.0 of AutoPkg, and it would be nice to build on the Python 3 compatibility adjustments made in this PR.

**Comment by apettinen** [comment]
Hi @homebysix ! Sorry for not replying earlier, I've been damn busy with (mostly non-technical) work and have had too little time to devote here... And yeah, I forgot the original message completely.

Anyhow, thanks for the PR, it looks fine by me. My plan was to spend some time in late December to work on my autopkg repos in order to make them Python3/AutoPkg2.0 compatible. Is that too late?

**Comment by homebysix** [comment]
No, I think late December should be fine. Even if AutoPkg 2.0 is released before then, uptake by Mac admins will probably be slow until the recipes/processors they depend on are updated.

**Comment by apettinen** [comment]
Cool, thanks for the info.

**Pull request merged**
