### PR TITLE
Update LuLu.munki.recipe

### PR DESCRIPTION
**Pull request by macmule**
Changes .munki to use the .download as parent, as a dmg is supplied.

This then generates an installs array looking at the .app on disk and not a pkg receipt created via AutoPkg.

```
Processing /Users/ben/Git/other-recipes/apettinen-recipes-1/LuLu/LuLu.munki.recipe...
WARNING: /Users/ben/Git/other-recipes/apettinen-recipes-1/LuLu/LuLu.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': 'LuLu_[\\d+?]{1,}.|_[\\d+?]{1,}.|_[\\d+?]{1,}.dmg',
           'github_repo': 'objective-see/LuLu',
           'include_prereleases': 'False'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting default value of: ~/.autopkg_gh_token
GitHubReleasesInfoProvider: Matched regex 'LuLu_[\d+?]{1,}.|_[\d+?]{1,}.|_[\d+?]{1,}.dmg' among asset(s): LuLu_2.3.1.dmg
GitHubReleasesInfoProvider: Selected asset 'LuLu_2.3.1.dmg' from release 'Version 2.3.1 '
{'Output': {'release_notes': 'Improved .dmg building process (#335)\r\n'
                             'UI Improvements, such as filter by pid (#323)\r\n'
                             'Improved handling of temporary rules (#322)\r\n'
                             'Refactored system extension / network filtering '
                             'approvals\r\n'
                             'Updated Network Monitor (Netiquette) to latest '
                             '(M1) version\r\n'
                             'Improved UI to prevent text overflowing buttons '
                             '(#309 / #326)',
            'url': 'https://github.com/objective-see/LuLu/releases/download/v2.3.1/LuLu_2.3.1.dmg',
            'version': '2.3.1'}}
URLDownloader
{'Input': {'url': 'https://github.com/objective-see/LuLu/releases/download/v2.3.1/LuLu_2.3.1.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Wed, 03 Mar 2021 21:25:26 GMT
URLDownloader: Storing new ETag header: "c83f62cad288393ccfaa3ed482486720"
URLDownloader: Downloaded /Users/ben/Library/AutoPkg/Cache/com.github.apettinen.munki.LuLu/downloads/LuLu_2.3.1.dmg
{'Output': {'download_changed': True,
            'etag': '"c83f62cad288393ccfaa3ed482486720"',
            'last_modified': 'Wed, 03 Mar 2021 21:25:26 GMT',
            'pathname': '/Users/ben/Library/AutoPkg/Cache/com.github.apettinen.munki.LuLu/downloads/LuLu_2.3.1.dmg',
            'url_downloader_summary_result': {'data': {'download_path': '/Users/ben/Library/AutoPkg/Cache/com.github.apettinen.munki.LuLu/downloads/LuLu_2.3.1.dmg'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'input_path': '/Users/ben/Library/AutoPkg/Cache/com.github.apettinen.munki.LuLu/downloads/LuLu_2.3.1.dmg/LuLu.app',
           'requirement': 'anchor apple generic and identifier '
                          '"com.objective-see.lulu.app" and (certificate '
                          'leaf[field.1.2.840.113635.100.6.1.9] /* exists */ '
                          'or certificate 1[field.1.2.840.113635.100.6.2.6] /* '
                          'exists */ and certificate '
                          'leaf[field.1.2.840.113635.100.6.1.13] /* exists */ '
                          'and certificate leaf[subject.OU] = VBG97UB4TA)'}}
CodeSignatureVerifier: Mounted disk image /Users/ben/Library/AutoPkg/Cache/com.github.apettinen.munki.LuLu/downloads/LuLu_2.3.1.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.OmdfLZ/LuLu.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.OmdfLZ/LuLu.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.OmdfLZ/LuLu.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
{'Output': {}}
MunkiImporter
{'Input': {'MUNKI_REPO': '/Users/Shared/munki_repo',
           'pkg_path': '/Users/ben/Library/AutoPkg/Cache/com.github.apettinen.munki.LuLu/downloads/LuLu_2.3.1.dmg',
           'pkginfo': {'catalogs': ['testing'],
                       'category': 'Security',
                       'description': 'LuLu is the free open-source macOS '
                                      'firewall aiming to block outgoing '
                                      'connections.',
                       'developer': 'Objective-See',
                       'display_name': 'LuLu Firewall',
                       'minimum_os_version': '10.15',
                       'name': 'LuLu',
                       'unattended_install': True,
                       'uninstall_script': '#!/bin/sh\n'
                                           '/bin/echo "killing the main app"\n'
                                           '/usr/bin/killall "LuLu" 2> '
                                           '/dev/null\n'
                                           '/bin/echo "Removing the main app"\n'
                                           '/bin/rm -rf '
                                           '/Applications/LuLu.app\n'
                                           '/bin/echo "removed the main app, '
                                           'killing the process"\n'
                                           '/usr/bin/killall '
                                           '"com.objective-see.luluHelper" 2> '
                                           '/dev/null\n'
                                           '/usr/bin/killall "LuLu Helper" 2> '
                                           '/dev/null\n'
                                           '/bin/echo "uninstall completed"\n'
                                           'exit 0\n'
                                           '            '},
           'repo_subdirectory': 'apps/LuLu'}}
MunkiImporter: No value supplied for MUNKI_REPO_PLUGIN, setting default value of: FileRepo
MunkiImporter: No value supplied for MUNKILIB_DIR, setting default value of: /usr/local/munki
MunkiImporter: No value supplied for force_munki_repo_lib, setting default value of: False
MunkiImporter: Using repo lib: AutoPkgLib
MunkiImporter:         plugin: FileRepo
MunkiImporter:           repo: /Users/Shared/munki_repo
MunkiImporter: Copied pkginfo to: /Users/Shared/munki_repo/pkgsinfo/apps/LuLu/LuLu-2.3.1.plist
MunkiImporter:            pkg to: /Users/Shared/munki_repo/pkgs/apps/LuLu/LuLu_2.3.1.dmg
{'Output': {'munki_importer_summary_result': {'data': {'catalogs': 'testing',
                                                       'icon_repo_path': '',
                                                       'name': 'LuLu',
                                                       'pkg_repo_path': 'apps/LuLu/LuLu_2.3.1.dmg',
                                                       'pkginfo_path': 'apps/LuLu/LuLu-2.3.1.plist',
                                                       'version': '2.3.1'},
                                              'report_fields': ['name',
                                                                'version',
                                                                'catalogs',
                                                                'pkginfo_path',
                                                                'pkg_repo_path',
                                                                'icon_repo_path'],
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'imported into '
                                                              'Munki:'},
            'munki_info': {'_metadata': {'created_by': 'ben',
                                         'creation_date': datetime.datetime(2021, 7, 19, 15, 12, 40),
                                         'munki_version': '5.5.0.4360',
                                         'os_version': '10.15.7'},
                           'autoremove': False,
                           'catalogs': ['testing'],
                           'category': 'Security',
                           'description': 'LuLu is the free open-source macOS '
                                          'firewall aiming to block outgoing '
                                          'connections.',
                           'developer': 'Objective-See',
                           'display_name': 'LuLu Firewall',
                           'installer_item_hash': 'adeaba9531d66ba8ffca4d5f6259e9cbf915afc8eb2cf604cabe5e4a721dc1fa',
                           'installer_item_location': 'apps/LuLu/LuLu_2.3.1.dmg',
                           'installer_item_size': 9432,
                           'installer_type': 'copy_from_dmg',
                           'installs': [{'CFBundleIdentifier': 'com.objective-see.lulu.app',
                                         'CFBundleName': 'LuLu',
                                         'CFBundleShortVersionString': '2.3.1',
                                         'CFBundleVersion': '2.3.1',
                                         'minosversion': '10.15',
                                         'path': '/Applications/LuLu.app',
                                         'type': 'application',
                                         'version_comparison_key': 'CFBundleShortVersionString'}],
                           'items_to_copy': [{'destination_path': '/Applications',
                                              'source_item': 'LuLu.app'}],
                           'minimum_os_version': '10.15',
                           'name': 'LuLu',
                           'unattended_install': True,
                           'uninstall_method': 'remove_copied_items',
                           'uninstall_script': '#!/bin/sh\n'
                                               '/bin/echo "killing the main '
                                               'app"\n'
                                               '/usr/bin/killall "LuLu" 2> '
                                               '/dev/null\n'
                                               '/bin/echo "Removing the main '
                                               'app"\n'
                                               '/bin/rm -rf '
                                               '/Applications/LuLu.app\n'
                                               '/bin/echo "removed the main '
                                               'app, killing the process"\n'
                                               '/usr/bin/killall '
                                               '"com.objective-see.luluHelper" '
                                               '2> /dev/null\n'
                                               '/usr/bin/killall "LuLu Helper" '
                                               '2> /dev/null\n'
                                               '/bin/echo "uninstall '
                                               'completed"\n'
                                               'exit 0\n'
                                               '            ',
                           'uninstallable': True,
                           'version': '2.3.1'},
            'munki_repo_changed': True,
            'pkg_repo_path': '/Users/Shared/munki_repo/pkgs/apps/LuLu/LuLu_2.3.1.dmg',
            'pkginfo_repo_path': '/Users/Shared/munki_repo/pkgsinfo/apps/LuLu/LuLu-2.3.1.plist'}}
Receipt written to /Users/ben/Library/AutoPkg/Cache/com.github.apettinen.munki.LuLu/receipts/LuLu.munki-receipt-20210719-161240.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/ben/Library/AutoPkg/Cache/com.github.apettinen.munki.LuLu/downloads/LuLu_2.3.1.dmg

The following new items were imported into Munki:
    Name  Version  Catalogs  Pkginfo Path                Pkg Repo Path             Icon Repo Path
    ----  -------  --------  ------------                -------------             --------------
    LuLu  2.3.1    testing   apps/LuLu/LuLu-2.3.1.plist  apps/LuLu/LuLu_2.3.1.dmg

```

### CODE REVIEW

**Comment by macmule** [comment]
bump :)

**Comment by paul-cossey** [comment]
Hi, @apettinen is there anything else you need to get @macmule's PR merged?

Thanks! :-)

**Comment by macmule** [comment]
👋

**Comment by macmule** [comment]
Created our own recipes - https://github.com/autopkg/dataJAR-recipes/tree/master/LuLu

**Pull request closed without merging**
